
http:
  pokemon:
    base: https://pokeapi.co/api/v2/
    api:
      ## if needed add other endpoints: berry, evolution, moves, etc..
      pokemon:
        ## other endpoints if needed
        pokemon_species: pokemon-species/
  shakespeare:
    base: https://api.funtranslations.com/translate/
    api:
      shakespeare: shakespeare
