server:
  port: 5000

request:
  threadpool:
    corepoolsize: 1
    maxpoolsize: 2
    threadpriority: 5 # default is 5 shared by all threadpools


http:
  pokemon:
    base: https://pokeapi.co/api/v2/
    api:
      ## if needed add other endpoints: berry, evolution, moves, etc..
      pokemon:
        ## other endpoints if needed
        pokemon_species: pokemon-species/
  shakespeare:
    base: http://localhost:4444/
    api:
      shakespeare: shakespeare
