
http:
  pokemon:
    ### For REMOTE test
    # base: https://pokeapi.co/api/v2/
    ### For LOCALHOST test
    base: http://localhost:4444/
    api:
      ### if needed add other endpoints: E.g. berry, evolution, moves, etc..
      pokemon:
        ### if needed add other endpoints for pokemon
        ### For REMOTE test
        # pokemon_species: pokemon-species/
        ### For LOCALHOST test
        pokemon_species: pokemon/
  shakespeare:
    ### For REMOTE test
    # base: https://api.funtranslations.com/translate/
    ### For LOCALHOST test
    pokemon_species: http://localhost:4444/
    api:
      ### For REMOTE test
      # shakespeare: shakespeare
      ### For LOCALHOST test
      shakespeare: shakespeare
